name: 'Auto Sign'

on:
  push:
    branches:
      - master
  schedule:
    - cron: '5 16,22 * * *'

jobs:
  sign:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2
      - name: 'Set python'
        uses: actions/setup-python@v1
        with:
          python-version: '3.6'
      - name: 'Install dependencies'
        run: python -m pip install --upgrade requests
      - name: 'Tieba Sign'
        env:
          BDUSS: ${{ secrets.BDUSS }}
        run: python module/main.py
      - name: '52pojie Sign'
          env:
            POJIECOOKIE: ${{ secrets.POJIECOOKIE }}
          run: python module/52pojie.py
        
